// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"
import NavbarController from "./navbar_controller"

const application = Application.start()
application.register("navbar", NavbarController)